### ISSUE TITLE
Error: ENOENT, no such file or directory 'ssl/server.key'

### ISSUE THREAD

**Issue by satizkrishna** [jkingsman/FreeStep#67] opened 2015-07-16 13:20 UTC
I was following the instructions and I could not resolve this one while starting the app.
 pls help

**Comment by jkingsman** [comment] 2015-07-16 15:19
This issue is caused by using the SSL setup code when you don't have keys in the expected location. Are you trying to run this with SSL? If not, just follow the README instructions on SSL (see "IMPORTANT SSL NOTE"). If yes, ensure that your key is in the `ssl` directory (which you will need to make), or change the location that express expects the key to be.

**Comment by jkingsman** [comment] 2015-07-16 15:20
^^ignore the closure... GitHub really needs to put those buttons further apart.

**Comment by jkingsman** [comment] 2015-08-03 23:31
Hi @satizkrishna - unless you're able to offer some more information, I'm going to go ahead and close this issue. Please feel free to reopen it in the future if the problem recurs or you have more information available about problem replication.

**Closed by jkingsman** 2015-08-03 23:31 UTC
